### ISSUE TITLE
recreate this in JS

### ISSUE THREAD

**Issue by AramRafeq** [sinaahmadi/wergor#1]
thank you for your contribution to kurdish language this repository would be very useful if you could recreate it using JS(javascript) i personally would use it everywhere in my projects to generate article and post slugs using titles, some tools exist for transliteration but not specific to Kurdish language most of the cases you should customize them and pass the mappings manually.

**Comment by sinaahmadi** [comment]
Hi Aram,

Thanks for your interest. 
I am afraid I would not have the time to do so, at least in the coming months. However, this might help you: [http://kurdinus.com/](http://kurdinus.com/). I don't know much about its performance, though. 

I'll have further updates, however, on this and other relevant projects. Please keep tuned. 

(if you cloned the repository recently, please pull the latest changes as I just noticed there was a bug in the transliteration of `û`).
